package main

import (
	"bytes"
	"fmt"
	"go/format"
	"strings"
	"text/template"
)

// arrayFieldBytes maps a field of tsvc.Arrays, used to validate and map a
// kernel parameter name (a, aa, ...) to the field it reads or writes, to the
// Go expression for that field's size in bytes.
//
// The scalars S1 and S2 are read from the register, not from memory, so they
// count no bytes.
var arrayFieldBytes = map[string]string{
	"A": "4*Len1D", "B": "4*Len1D", "C": "4*Len1D", "D": "4*Len1D", "E": "4*Len1D", "X": "4*Len1D",
	"AA": "4*Len2D*Len2D", "BB": "4*Len2D*Len2D", "CC": "4*Len2D*Len2D",
	"S1": "", "S2": "", "N1": "", "N3": "",
	"FLAT_2D_ARRAY": "4*Len2D*Len2D",
}

// checksumFuncs maps a checksum=<value> directive to the sum and hash
// function names in package tsvc.
var checksumFuncs = map[string][2]string{
	"a":  {"sumA", "hashA"},
	"x":  {"sumX", "hashX"},
	"aa": {"sumAA", "hashAA"},

	"flat_2d_array": {"sumFlat2DArray", "hashFlat2DArray"},
	"a+b":           {"sumAB", "hashAB"},
	"a+b+c":         {"sumABC", "hashABC"},
	"aa+bb":         {"sumAABB", "hashAABB"},
	"a+aa":          {"sumAAndAA", "hashAAndAA"},
	"xx0":           {"sumXX0", "hashXX0"},
	"xx4":           {"sumXX4", "hashXX4"},
	"xx63":          {"sumXX63", "hashXX63"},
	"half_xx":       {"sumHalfXX", "hashHalfXX"},
	"r":             {"sumR", "hashR"},
}

// exactConsts maps an exact=<value> directive to its Exactness constant.
var exactConsts = map[string]string{
	"bits":    "ExactBits",
	"fused":   "ExactFused",
	"reassoc": "ExactReassoc",
}

// expectConsts maps an expect=<value> directive to its Expectation constant.
var expectConsts = map[string]string{
	"vectorize": "ExpectVectorize",
	"decline":   "ExpectDecline",
	"skip":      "ExpectSkip",
}

// categoryConsts maps a category=<value> directive to its Category constant.
var categoryConsts = map[string]string{
	"dependence": "CategoryDependence",
	"control":    "CategoryControl",

	"induction":       "CategoryInduction",
	"dataflow":        "CategoryDataFlow",
	"interprocedural": "CategoryInterprocedural",
	"controlflow":     "CategoryControlFlow",
	"symbolics":       "CategorySymbolics",
	"reordering":      "CategoryReordering",
	"distribution":    "CategoryDistribution",
	"interchange":     "CategoryInterchange",
	"nodesplitting":   "CategoryNodeSplitting",
	"expansion":       "CategoryExpansion",
	"thresholds":      "CategoryThresholds",
	"peeling":         "CategoryPeeling",
	"diagonals":       "CategoryDiagonals",
	"reductions":      "CategoryReductions",
	"rerolling":       "CategoryRerolling",
	"equivalencing":   "CategoryEquivalencing",
	"parameters":      "CategoryParameters",
	"nonlogicalifs":   "CategoryNonLogicalIfs",
	"intrinsics":      "CategoryIntrinsics",
	"indirect":        "CategoryIndirect",
	"nonlinear":       "CategoryNonlinear",
	"search":          "CategorySearch",
}

// entry is the data a directive renders as, one per Kernels table row.
type entry struct {
	Name     string
	Category string
	Reps     int
	Exact    string
	Expect   string
	Setup    string
	Checksum string
	Hash     string
	Bytes    string
	RunArgs  string
	FuncName string
	// Assign is "x.R = " for a kernel that returns a value, which the registry
	// stores in Arrays.R for the checksum to read.
	Assign string
}

func toEntry(d directive) (entry, error) {
	category, ok := categoryConsts[d.Category]
	if !ok {
		return entry{}, fmt.Errorf("%s: unknown category %q", d.Pos, d.Category)
	}
	exact, ok := exactConsts[d.Exact]
	if !ok {
		return entry{}, fmt.Errorf("%s: unknown exact %q", d.Pos, d.Exact)
	}
	expect, ok := expectConsts[d.Expect]
	if !ok {
		return entry{}, fmt.Errorf("%s: unknown expect %q", d.Pos, d.Expect)
	}
	checksum, ok := checksumFuncs[d.Checksum]
	if !ok {
		return entry{}, fmt.Errorf("%s: unknown checksum %q", d.Pos, d.Checksum)
	}

	assign := ""
	if d.Returns {
		assign = "x.R = "
	}
	args := make([]string, len(d.Params))
	var sizes []string
	for i, p := range d.Params {
		field := strings.ToUpper(p)
		size, ok := arrayFieldBytes[field]
		if !ok {
			return entry{}, fmt.Errorf("%s: parameter %q has no matching Arrays field", d.Pos, p)
		}
		args[i] = "x." + field
		if size != "" {
			sizes = append(sizes, size)
		}
	}
	if len(sizes) == 0 {
		sizes = []string{"0"}
	}

	return entry{
		Name:     d.FuncName,
		Category: category,
		Reps:     d.Reps,
		Exact:    exact,
		Expect:   expect,
		Setup:    "setup" + strings.ToUpper(d.Setup[:1]) + d.Setup[1:],
		Checksum: checksum[0],
		Hash:     checksum[1],
		Bytes:    strings.Join(sizes, " + "),
		RunArgs:  strings.Join(args, ", "),
		FuncName: d.FuncName,
		Assign:   assign,
	}, nil
}

var registryTmpl = template.Must(template.New("registry").Parse(`// Code generated by tsvcgen. DO NOT EDIT.

package tsvc

// Kernels lists the ported kernels, in TSVC_2 source order.
var Kernels = []Kernel{
{{range .}}	{
		Name: "{{.Name}}", Category: {{.Category}}, Reps: {{.Reps}}, Exact: {{.Exact}}, Expect: {{.Expect}},
		Bytes: {{.Bytes}},
		Setup: {{.Setup}}, Checksum: {{.Checksum}}, Hash: {{.Hash}},
		Run: func(x *Arrays) { {{.Assign}}{{.FuncName}}({{.RunArgs}}) },
	},
{{end}}}
`))

// generate renders the Kernels table for directives, in the order given.
func generate(directives []directive) ([]byte, error) {
	entries := make([]entry, len(directives))
	for i, d := range directives {
		e, err := toEntry(d)
		if err != nil {
			return nil, err
		}
		entries[i] = e
	}

	var buf bytes.Buffer
	if err := registryTmpl.Execute(&buf, entries); err != nil {
		return nil, err
	}
	return format.Source(buf.Bytes())
}
