package main

import (
	"bytes"
	"fmt"
	"go/format"
	"strings"
	"text/template"
)

// arrayFields are the fields of tsvc.Arrays, used to validate and map a
// kernel parameter name (a, aa, ...) to the field it reads or writes.
var arrayFields = map[string]bool{
	"A": true, "B": true, "C": true, "D": true, "E": true,
	"AA": true, "BB": true, "CC": true,
}

// checksumFuncs maps a checksum=<value> directive to the sum and hash
// function names in package tsvc.
var checksumFuncs = map[string][2]string{
	"a":  {"sumA", "hashA"},
	"aa": {"sumAA", "hashAA"},
}

// exactConsts maps an exact=<value> directive to its Exactness constant.
var exactConsts = map[string]string{
	"bits":  "ExactBits",
	"fused": "ExactFused",
}

// categoryConsts maps a category=<value> directive to its Category constant.
var categoryConsts = map[string]string{
	"dependence": "CategoryDependence",
}

// entry is the data a directive renders as, one per Kernels table row.
type entry struct {
	Name     string
	Category string
	Reps     int
	Exact    string
	Setup    string
	Checksum string
	Hash     string
	RunArgs  string
	FuncName string
}

func toEntry(d directive) (entry, error) {
	category, ok := categoryConsts[d.Category]
	if !ok {
		return entry{}, fmt.Errorf("%s: unknown category %q", d.Pos, d.Category)
	}
	exact, ok := exactConsts[d.Exact]
	if !ok {
		return entry{}, fmt.Errorf("%s: unknown exact %q", d.Pos, d.Exact)
	}
	checksum, ok := checksumFuncs[d.Checksum]
	if !ok {
		return entry{}, fmt.Errorf("%s: unknown checksum %q", d.Pos, d.Checksum)
	}

	args := make([]string, len(d.Params))
	for i, p := range d.Params {
		field := strings.ToUpper(p)
		if !arrayFields[field] {
			return entry{}, fmt.Errorf("%s: parameter %q has no matching Arrays field", d.Pos, p)
		}
		args[i] = "x." + field
	}

	return entry{
		Name:     d.FuncName,
		Category: category,
		Reps:     d.Reps,
		Exact:    exact,
		Setup:    "setup" + strings.ToUpper(d.Setup[:1]) + d.Setup[1:],
		Checksum: checksum[0],
		Hash:     checksum[1],
		RunArgs:  strings.Join(args, ", "),
		FuncName: d.FuncName,
	}, nil
}

var registryTmpl = template.Must(template.New("registry").Parse(`// Code generated by tsvcgen. DO NOT EDIT.

package tsvc

// Kernels lists the ported kernels, in TSVC_2 source order.
var Kernels = []Kernel{
{{range .}}	{
		Name: "{{.Name}}", Category: {{.Category}}, Reps: {{.Reps}}, Exact: {{.Exact}},
		Setup: {{.Setup}}, Checksum: {{.Checksum}}, Hash: {{.Hash}},
		Run: func(x *Arrays) { {{.FuncName}}({{.RunArgs}}) },
	},
{{end}}}
`))

// generate renders the Kernels table for directives, in the order given.
func generate(directives []directive) ([]byte, error) {
	entries := make([]entry, len(directives))
	for i, d := range directives {
		e, err := toEntry(d)
		if err != nil {
			return nil, err
		}
		entries[i] = e
	}

	var buf bytes.Buffer
	if err := registryTmpl.Execute(&buf, entries); err != nil {
		return nil, err
	}
	return format.Source(buf.Bytes())
}
