// Code generated by "stringer -type=Category -trimprefix=Category"; DO NOT EDIT.

package tsvc

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[CategoryDependence-0]
	_ = x[CategoryControl-1]
}

const _Category_name = "DependenceControl"

var _Category_index = [...]uint8{0, 10, 17}

func (i Category) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_Category_index)-1 {
		return "Category(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Category_name[_Category_index[idx]:_Category_index[idx+1]]
}
