// Code generated by tsvcgen. DO NOT EDIT.

package tsvc

// Kernels lists the ported kernels, in TSVC_2 source order.
var Kernels = []Kernel{
	{
		Name: "s000", Category: CategoryDependence, Reps: 2, Exact: ExactBits, Expect: ExpectVectorize,
		Bytes: 4*Len1D + 4*Len1D,
		Setup: setupS000, Checksum: sumA, Hash: hashA,
		Run: func(x *Arrays) { s000(x.A, x.B) },
	},
	{
		Name: "s111", Category: CategoryDependence, Reps: 2, Exact: ExactBits, Expect: ExpectVectorize,
		Bytes: 4*Len1D + 4*Len1D,
		Setup: setupS111, Checksum: sumA, Hash: hashA,
		Run: func(x *Arrays) { s111(x.A, x.B) },
	},
	{
		Name: "s1111", Category: CategoryDependence, Reps: 2, Exact: ExactFused, Expect: ExpectVectorize,
		Bytes: 4*Len1D + 4*Len1D + 4*Len1D + 4*Len1D,
		Setup: setupS111, Checksum: sumA, Hash: hashA,
		Run: func(x *Arrays) { s1111(x.A, x.B, x.C, x.D) },
	},
	{
		Name: "s112", Category: CategoryDependence, Reps: 3, Exact: ExactBits, Expect: ExpectVectorize,
		Bytes: 4*Len1D + 4*Len1D,
		Setup: setupS112, Checksum: sumA, Hash: hashA,
		Run: func(x *Arrays) { s112(x.A, x.B) },
	},
	{
		Name: "s1112", Category: CategoryDependence, Reps: 3, Exact: ExactBits, Expect: ExpectVectorize,
		Bytes: 4*Len1D + 4*Len1D,
		Setup: setupS112, Checksum: sumA, Hash: hashA,
		Run: func(x *Arrays) { s1112(x.A, x.B) },
	},
	{
		Name: "s113", Category: CategoryDependence, Reps: 4, Exact: ExactBits, Expect: ExpectVectorize,
		Bytes: 4*Len1D + 4*Len1D,
		Setup: setupS113, Checksum: sumA, Hash: hashA,
		Run: func(x *Arrays) { s113(x.A, x.B) },
	},
	{
		Name: "s1113", Category: CategoryDependence, Reps: 2, Exact: ExactBits, Expect: ExpectVectorize,
		Bytes: 4*Len1D + 4*Len1D,
		Setup: setupS113, Checksum: sumA, Hash: hashA,
		Run: func(x *Arrays) { s1113(x.A, x.B) },
	},
	{
		Name: "s114", Category: CategoryDependence, Reps: 1, Exact: ExactBits, Expect: ExpectDecline,
		Bytes: 4*Len2D*Len2D + 4*Len2D*Len2D,
		Setup: setupS114, Checksum: sumAA, Hash: hashAA,
		Run: func(x *Arrays) { s114(x.AA, x.BB) },
	},
	{
		Name: "s115", Category: CategoryDependence, Reps: 1, Exact: ExactFused, Expect: ExpectVectorize,
		Bytes: 4*Len1D + 4*Len2D*Len2D,
		Setup: setupS115, Checksum: sumA, Hash: hashA,
		Run: func(x *Arrays) { s115(x.A, x.AA) },
	},
	{
		Name: "s1115", Category: CategoryDependence, Reps: 1, Exact: ExactFused, Expect: ExpectDecline,
		Bytes: 4*Len2D*Len2D + 4*Len2D*Len2D + 4*Len2D*Len2D,
		Setup: setupS115, Checksum: sumAA, Hash: hashAA,
		Run: func(x *Arrays) { s1115(x.AA, x.BB, x.CC) },
	},
	{
		Name: "va", Category: CategoryControl, Reps: 4, Exact: ExactBits, Expect: ExpectVectorize,
		Bytes: 4*Len1D + 4*Len1D,
		Setup: setupVpv, Checksum: sumA, Hash: hashA,
		Run: func(x *Arrays) { va(x.A, x.B) },
	},
	{
		Name: "vif", Category: CategoryControl, Reps: 4, Exact: ExactBits, Expect: ExpectVectorize,
		Bytes: 4*Len1D + 4*Len1D,
		Setup: setupVpv, Checksum: sumA, Hash: hashA,
		Run: func(x *Arrays) { vif(x.A, x.B) },
	},
	{
		Name: "vpv", Category: CategoryControl, Reps: 4, Exact: ExactBits, Expect: ExpectVectorize,
		Bytes: 4*Len1D + 4*Len1D,
		Setup: setupVpv, Checksum: sumA, Hash: hashA,
		Run: func(x *Arrays) { vpv(x.A, x.B) },
	},
	{
		Name: "vtv", Category: CategoryControl, Reps: 4, Exact: ExactBits, Expect: ExpectVectorize,
		Bytes: 4*Len1D + 4*Len1D,
		Setup: setupVtv, Checksum: sumA, Hash: hashA,
		Run: func(x *Arrays) { vtv(x.A, x.B) },
	},
	{
		Name: "vpvtv", Category: CategoryControl, Reps: 4, Exact: ExactFused, Expect: ExpectVectorize,
		Bytes: 4*Len1D + 4*Len1D + 4*Len1D,
		Setup: setupVpvtv, Checksum: sumA, Hash: hashA,
		Run: func(x *Arrays) { vpvtv(x.A, x.B, x.C) },
	},
	{
		Name: "vpvts", Category: CategoryControl, Reps: 4, Exact: ExactFused, Expect: ExpectVectorize,
		Bytes: 4*Len1D + 4*Len1D,
		Setup: setupVpvts, Checksum: sumA, Hash: hashA,
		Run: func(x *Arrays) { vpvts(x.A, x.B, x.S1) },
	},
	{
		Name: "vpvpv", Category: CategoryControl, Reps: 4, Exact: ExactBits, Expect: ExpectVectorize,
		Bytes: 4*Len1D + 4*Len1D + 4*Len1D,
		Setup: setupVpvpv, Checksum: sumA, Hash: hashA,
		Run: func(x *Arrays) { vpvpv(x.A, x.B, x.C) },
	},
	{
		Name: "vtvtv", Category: CategoryControl, Reps: 4, Exact: ExactBits, Expect: ExpectVectorize,
		Bytes: 4*Len1D + 4*Len1D + 4*Len1D,
		Setup: setupVtvtv, Checksum: sumA, Hash: hashA,
		Run: func(x *Arrays) { vtvtv(x.A, x.B, x.C) },
	},
	{
		Name: "vbor", Category: CategoryControl, Reps: 4, Exact: ExactFused, Expect: ExpectVectorize,
		Bytes: 4*Len1D + 4*Len1D + 4*Len1D + 4*Len1D + 4*Len1D + 4*Len2D*Len2D + 4*Len1D,
		Setup: setupVbor, Checksum: sumX, Hash: hashX,
		Run: func(x *Arrays) { vbor(x.A, x.B, x.C, x.D, x.E, x.AA, x.X) },
	},
}
